### ISSUE TITLE
bank vat terminated; cannot start solo wallet client

### ISSUE THREAD

**Issue by Syd-ai** [Agoric/testnet-notes#7]
Hello,

I have some trouble to connect to the client. It seems I'm trying to connect but it gets terminated each time. On the Browser I see some quick connections and disconnections.

Tried to restart the ag-solo docker
Tried to restart with -v flag
Tried to reinstall docker compose and engine

Nothing seems to work.

Logs attached,
Thanks in advance for your help

[docker-compose logs.txt](https://github.com/Agoric/dapp-treasury/files/6463637/docker-compose.logs.txt)

**Comment by dckc** [comment]
@warner @michaelfig I'm struggling to figure out which vat this "vat terminated" error applies to; any suggestions on how to diagnose?

**Comment by dckc** [comment]
@warner reports the bank vat exited at 2021-05-12T02:02:42.175Z (`time":1620784962.175039`).

**Comment by easy2stake** [comment]
We do have the same issue here with the testnet docker-compose.yml.

[complet-logs-error-starting-compose.txt](https://github.com/Agoric/testnet-notes/files/6468306/complet-logs-error-starting-compose.txt)

**Comment by dckc** [comment]
See also
 - [#3085](https://github.com/Agoric/agoric-sdk/issues/3085) phase3 testnet (act 2) killed by SIGSEGV of vat-bank worker

**Comment by sshamanov** [comment]
Same issue

[agoric1qq8tgungfppa68rfgp26pwkeyl474zvduywyax.txt](https://github.com/Agoric/testnet-notes/files/6469010/agoric1qq8tgungfppa68rfgp26pwkeyl474zvduywyax.txt)
[agoric17szedptrthu5chq28essful6scu3jsx6f6ec8n.txt](https://github.com/Agoric/testnet-notes/files/6469037/agoric17szedptrthu5chq28essful6scu3jsx6f6ec8n.txt)
[agoric1rdkg868a6fkwkzw9ypl2yy8hez84n8qaetdeh6.txt](https://github.com/Agoric/testnet-notes/files/6469038/agoric1rdkg868a6fkwkzw9ypl2yy8hez84n8qaetdeh6.txt)

clean docker 20.10.2-0ubuntu1~20.04.2 install, each log from the separate VM ubuntu 20.04.2

**Comment by kj89** [comment]
upgraded docker container and have same error described above

**Comment by michaelfig** [comment]
# Public Service Announcement

The phase3 bank vat died (#3085).  That process provides a link between certain Agoric wallet purses and the Cosmos balances.

Because of this, you can't transfer assets from the Agoric VM wallet to the Cosmos layer.  Cosmos balances of `ubld` and `urun` are intact and can still be manipulated by `ag-cosmos-helper`.

Don't worry!  Please fill out the only task you cannot complete (increase your BLD) with "vat-bank is broken".  We will not penalise people who are affected by this bug.

I'm closing the comments so that people can focus on this answer and not confuse others who come to this issue.
